### PR TITLE
Basic utilities of java.net for easy and direct access of various frequent methods.

### PR DESCRIPTION
**Pull request by arglee**
Adding basic utilities similar to java.net for frequent access of very basic methods.
This includes:

- getHost
- getPort
- getProtocol
- getDefaultPort
- getUserInfo
- getRef
- getFile
- getContent etc. 
For all the methods added, please refer to [link](https://github.com/arglee/scalaj-http/blob/fbb753a7269fff1a6d9a03245346e70ef0299d58/src/main/scala/scalaj/http/Http.scala#L477).

### CODE REVIEW

**Comment by hoffrocket** [comment]
Hi, thanks for these suggestions, but they do not work well with the design goals of this library. If you want to use the java Url library for connections, that's totally reasonable, but I don't understand the use case for a thin wrapper on those methods. This library already provides a more robust wrapper around the built in java http libraries. If you can describe the problem you are trying to solve, I might be able to suggest ways to solve given existing functionality.

**Comment by arglee** [comment]
Hi, thanks for reply. Many time I have a situation where I don't know about url. in those cases I need to know about internal information about URL also.
I am describing a very specific situation that I faced as below:

**API response**:
```
{
    "url": "some_random_url",
    "......
}
```

Now there is a job that needs to parse this URL and on the basis of hostname and other above-mentioned properties, it takes decisions. and then finally returns the response to API.

In such cases this is very helpful if we can provide a thin wrapper over java.net.URL, so that we dont need to pass above URL into `val url = new URL("http://.../...?t=t1")`.

**Comment by hoffrocket** [comment]
I think using java.net.URL without another wrapper is probably the best
approach for you

**Comment by arglee** [comment]
Yeah, but if we are already providing some input to HTTP System(in this case scalaj-http), then it should have the responsibility to provide very basic discrete information about the input. and getting the hostname and port is a very common thing. This is the approach what as far as I was thinking during implementation.

**Pull request closed without merging**
