### PR TITLE
add new method to add body, fix typo and change method for consistency

### PR DESCRIPTION
**Pull request by samupra**

### CODE REVIEW

**Comment by samupra** [comment]
@hoffrocket  Please review the pull request! :) I use the library heavily and would love to see these functions included. Thank you so much for your time!

**Comment by samupra** [comment]
@hoffrocket  I am also planning to add some async features. Let me know if you're interested in those!

**Comment by hoffrocket** [comment]
Hi @samupra, I appreciate your thoughts and use of the library, but I don't think theses changes should be included for a couple of reasons:
1. The renaming of the functions (`put` to `putData`) would be a breaking change for existing users
2. I don't think the introduction of `withData` provides that much value over chaining `body().method()`. Also, I'm not sure if the HTTP specification prohibits a message-body on methods other than `PUT` and `POST`-- in any case, I don't see a reason to guard against it client side.

In your own usage of the library, you can create higher level wrappers to provide better names or enforcement.

**Comment by samupra** [comment]
@hoffrocket  how would you feel about adding another function with the name putData while keeping the original put? While using the library, it was almost instinctive to use a putData method after postData. However, if you don't see the use in it, I won't work on it 👍

**Pull request closed without merging**
